# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mC9f5lcxCU-GogBk5fGqYfZjJvTubOJC
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import KroghInterpolator, CubicHermiteSpline

def f(x):
    return x**3 + 4

def g(x):
    return np.log(x + 1)
  #fcts de derives pour hermit
def df(x):
    return 3 * x**2

def dg(x):
    return 1 / (x + 1)

  #fct de lagrange
def lagrange(x, x_points, y_points):
    x = np.asarray(x, dtype=float)
    rslt = np.zeros_like(x)
    for i in range(len(x_points)):
        L = np.ones_like(x)
        for j in range(len(x_points)):
            if i != j:
                L *= (x - x_points[j]) / (x_points[i] - x_points[j])
        rslt += y_points[i] * L
    return rslt


x_plot = np.linspace(0, 3, 500)
valeurs = [3, 5, 10, 15]

  #fcts de newton et hermit
for func, dfunc, name in [(f, df, 'f(x) = x³ + 4'),
                          (g, dg, 'g(x) = ln(x+1)')]:
    plt.figure(figsize=(12, 8))
    plt.plot(x_plot, func(x_plot), 'k-', label='Fonction originale', linewidth=2)

    for N in valeurs:
        x_points = np.linspace(0, 3, N)
        y_points = func(x_points)

        y_lagrange = lagrange(x_plot, x_points, y_points)
        plt.plot(x_plot, y_lagrange, '--', label=f'Lagrange N={N}')

        newton_interp = KroghInterpolator(x_points, y_points)
        plt.plot(x_plot, newton_interp(x_plot), ':', label=f'Newton N={N}')

        dy_points = dfunc(x_points)
        hermite_interp = CubicHermiteSpline(x_points, y_points, dy_points)
        plt.plot(x_plot, hermite_interp(x_plot), '-.', label=f'Hermite N={N}')

    plt.title(f'Interpolation de {name}')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.legend()
    plt.grid(True)
    plt.show()